apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: hello-openshift
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: hello-openshift
    app.kubernetes.io/name: hello-openshift
    app.kubernetes.io/part-of: hello-openshift
    app.openshift.io/runtime: java
  name: hello-openshift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        imagePullPolicy: Always
        image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
        ports:
        - containerPort: 8080
          protocol: TCP
