apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs
  namespace: openshift-gitops
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: cluster
    repoURL: https://github.com/ralvares/openshift-gitops-hacking
    targetRevision: HEAD
